name: Deploy to Render
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout the repo/code
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20.x'
      - name: Setup Docker Builder
        uses: docker/setup-buildx-action@v2

      - name: Login to docket hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lesson8mongoose:latest
          build-args:
            MONGO_URI=${{ secrets.MONGO_URI }}

      # - name: Install dependencies
      #   run: npm install

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}



          
